### ISSUE TITLE
mvp tests

### ISSUE THREAD

**Issue by aaronArinder** [aaronArinder/mobile-disposition-tracker#13]
#### problem
We've no tests!

#### to-dos
- [ ] save button actually saves to db
- [ ] save button non-functional with invalid fields
- [ ] data saved to db is timestamped
- [ ] data populates on app load
- [ ] data shown in proper order (most recent entry first)
