### ISSUE TITLE
field validation for disposition/context inputs

### ISSUE THREAD

**Issue by aaronArinder** [aaronArinder/mobile-disposition-tracker#14]
#### problem
We're letting users save empty fields, but that serves no purpose. At the minimum, we should have a validation check for the disposition field being empty. We'll eventually rely heavily on context, so, we should likely validate that field, too. This bears more thinking, though, since there might cases where a user doesn't want to include a context.

#### to-dos
- [ ] validate empty disposition field
  - [ ] save button disabled
  - [ ] BE check for empty disposition field
- [ ] decide whether to validate empty context field
  - [ ] if so, save button disabled
  - [ ] if so, BE check for empty context field
