### ISSUE TITLE
comment App.vue

### ISSUE THREAD

**Issue by aaronArinder** [aaronArinder/mobile-disposition-tracker#5]
#### problem
Currently, this is the meat/potatoes of the app: we should give an overview of its structure, and any gotchas that stick out.

#### to-dos
- [ ] comment the export, especially `data` and its `query` dispatch
- [ ] comment on the purpose/use of methods
- [ ] comment on the differences between native-script's implementation of vue and proper vue, noting any gotchas that arise from it (e.g., what's available in vue that's not in native-script's vue port?)
